# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e685c4a4605c6ffc717496347d80822dfa085885ff74f5ba201eb1848e45a9ccc1ea35a4841207445c7e6606317db389be63c25734bb52009ad647b51944c964

test:
  secret_key_base: 765de358c36274c5add6689f38c126b3a5daf73a2be3dc1d450217e046e23582e8a5a44bdb860582f15349df6f011057ca3c69f588b28049a14abdae7cde2360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
